CREATE OR REPLACE PACKAGE TIPO_DATOS IS
VREG_SALARIO EMPLEADOS.SALARIO%ROWTYPE := NEW;
VREG_COMISION EMPLEADOS.COMISION%ROWTYPE :=NEW;
VREG_COD_OFICINAS EMPLEADOS.CODIGOOFICINAS%ROWTYPE :=OLD;
VREG_CIUDAD EMPLEADOS.CIUDAD%ROWTYPE := OLD;
VREG_PAIS EMPLEADOS.PAIS%ROWTYPE := OLD;
VREG_REGION EMPLEADOS.REGION%ROWTYPE :=OLD;
VREG_COD_POSTAL EMPLEADOS.CODIGOPOSTAL%ROWTYPE := OLD;
VREG_TELEFONO EMPLEADOS.TELEFONO%ROWTYPE :=OLD;
VREG_LIN_DIR1 EMPLEADOS.LINEADIRECCION1%ROWTYPE := OLD;
VREG_LIN_DIR2 EMPLEADOS.LINEADIRECCION2%ROWTYPE :=OLD;
END;

