/*Consultar el código de empleado y el número de clientes al que atiende cada empleado que es representante de ventas. 
Las cabeceras serán respectivamente “Código del Empleado” y “Clientes que atiende”*/
SELECT E.NOMBRE AS "NOMBRE DEL EMPLEADO",E.CODIGOEMPLEADO AS "CODIGO DE EMPLEADO", COUNT(C.CodigoEmpleadoRepVentas) AS "CLIENTES QUE ATIENDE"
FROM EMPLEADOS E, CLIENTES C
WHERE E.CODIGOEMPLEADO=C.CodigoEmpleadoRepVentas 
AND
UPPER(E.PUESTO)='REPRESENTANTE VENTAS'
GROUP BY E.CODIGOEMPLEADO, E.NOMBRE
ORDER BY CODIGOEMPLEADO;

SELECT E.NOMBRE AS "NOMBRE DEL EMPLEADO",E.CODIGOEMPLEADO AS "CODIGO DE EMPLEADO", COUNT(C.CodigoEmpleadoRepVentas) AS "CLIENTES QUE ATIENDE"
FROM EMPLEADOS E, CLIENTES C
WHERE E.CODIGOEMPLEADO(+)=C.CodigoEmpleadoRepVentas 
AND
UPPER(E.PUESTO)='REPRESENTANTE VENTAS'
GROUP BY E.CODIGOEMPLEADO, E.NOMBRE
ORDER BY CODIGOEMPLEADO;

/*Listar el nombre de los clientes que hayan hecho pedidos en 2008.*/
SELECT DISTINCT C.NOMBRECLIENTE
FROM CLIENTES C, PEDIDOS P
WHERE C.NOMBRECLIENTE=P.CODIGOCLIENTE
AND P.FECHAPEDIDO BETWEEN TO_DATE('2008-01-01')AND (TO_DATE('2008-12-31'));
